### ISSUE TITLE
False reports and/or `// swift-format-ignore: DontRepeatTypeInStaticProperties` doesn't work.

### ISSUE THREAD

**Issue by thomasvl** [swiftlang/swift-format#816] opened 2024-09-24 15:04 UTC
1. Checkout https://github.com/apple/swift-protobuf @ c9fbc332ed293c64ff70af8d82367ca530dce11c
1. `swift format lint Sources/SwiftProtobuf/Message.swift` - Will produce a warning:

    > Sources/SwiftProtobuf/Message.swift:46:16: warning: [DontRepeatTypeInStaticProperties] remove the suffix 'Message' from the name of the variable 'protoMessageName'

1. Apply this diff:
    ```diff
    diff --git a/Sources/SwiftProtobuf/Message.swift b/Sources/SwiftProtobuf/Message.swift
    index 4d59ab93..8ebbb1e5 100644
    --- a/Sources/SwiftProtobuf/Message.swift
    +++ b/Sources/SwiftProtobuf/Message.swift
    @@ -43,6 +43,7 @@ public protocol Message: Sendable, CustomDebugStringConvertible {
     
         /// The fully-scoped name of the message from the original .proto file,
         /// including any relevant package name.
    +    // swift-format-ignore: DontRepeatTypeInStaticProperties
         static var protoMessageName: String { get }
     
         /// True if all required fields (if any) on this message and any nested
    ```

1. `swift format lint Sources/SwiftProtobuf/Message.swift` - will still produce the warning (just with the line number increased correctly)

    > Sources/SwiftProtobuf/Message.swift:47:16: warning: [DontRepeatTypeInStaticProperties] remove the suffix 'Message' from the name of the variable 'protoMessageName'

Likely issues:
-  I'm not sure the warning is correct since "Message" isn't the suffix, it's actually _Name_ or _MessageName_
-  The comment to suppress doesn't suppress.

**Comment by ahoppen** [comment] 2024-09-24 16:03
Synced to Apple’s issue tracker as rdar://136589532

**Comment by ahoppen** [comment] 2024-10-14 17:59
Duplicate of https://github.com/swiftlang/swift-format/issues/771

**Closed by ahoppen** 2024-10-14 17:59 UTC

**Comment by thomasvl** [comment] 2024-10-14 19:03
@ahoppen so that duplicate might by why the suppression doesn't work, but the error here is also pretty odd. The variable does not end in "Message" as the message suggests.  I have a feeling there is also something else wrong in the check.

**Comment by ahoppen** [comment] 2024-10-14 19:33
Oh, thanks. I missed the part about the message being incorrect here.
