### ISSUE TITLE
Formatter does not know about the `sending` keyword

### ISSUE THREAD

**Issue by BastianKusserow** [swiftlang/swift-format#814] opened 2024-09-24 13:48 UTC
Whenever formatting a file that uses `sending` parameters, swift format fails with an error.

```swift
public struct Box<Value> {
    public init(_ initialValue: sending Value) {
    }
}
```

Trying to format that code yields "unexpected code 'Value' in parameter clause". I tried that with the `release/6.0.2` branch as well as with the swift format version that ships with Xcode 16.

**Comment by allevato** [comment] 2024-09-24 13:56
Duplicate of https://github.com/swiftlang/swift-syntax/issues/2836 (the issue is in the parser, not the formatter).

**Closed by allevato** 2024-09-24 13:56 UTC

**Comment by BastianKusserow** [comment] 2024-09-24 14:09
I see, thanks for the quick reply!
